### ISSUE TITLE
OR operator for filtering within variable

### ISSUE THREAD

**Issue by wisepotato** [json-api-dotnet/JsonApiDotNetCore#435] opened 2018-10-22 15:01 UTC
## Description

I think the current filtering system is lacking. I think an implementation akin to OData would serve us well here.

The current implementation does not handle OR operators and I think we would be needlessly complicating things by using the current system. 

Any ideas on future implementation of OR/AND combinations which are currently.. less than ideal?

an example:

`((name like John) and (lastname like Pappa)) OR (name like P-diddy) OR (lastname like eminem`

## Environment

- JsonApiDotNetCore Version: 
- Other Relevant Package Versions:

**Comment by jaredcnance** [comment] 2018-10-22 15:41
Duplicate of #183

**Closed by jaredcnance** 2018-10-22 15:41 UTC
