### ISSUE TITLE
Also include next and totalResources for nested resources.

### ISSUE THREAD

**Issue by databrecht** [json-api-dotnet/JsonApiDotNetCore#1035] opened 2021-07-20 13:22 UTC
**Is your feature request related to a problem? Please describe.**
Retrieving a set of date entities returns, for example with: 

- api/v1/devices

Results in next links and total resources. 

```
{
meta: {
  totalResources: 3
},
links: {
  self: "/api/v1/devices?page[size]=2",
  first: "/api/v1/devices?page[size]=2",
  last: "/api/v1/devices?page[size]=2&page[number]=2",
  next: "/api/v1/devices?page[size]=2&page[number]=2"
},
data: [...
```

However, when calling a nested endpoint which contains a list of data entities such as: 

- api/v1/locations/<id>/devices

It seems that **totalResources** as well as the **next** link is not included in the result which makes it hard for the client to paginate. Pagination works (the query parameters can be used) but the links and information of the total number of resources is omitted in the json result. 

```
{
links: {
  self: "/api/v1/locations/008b34d8-7dfe-40f1-a422-3bff500744b8/devices",
  first: "/api/v1/locations/008b34d8-7dfe-40f1-a422-3bff500744b8/devices"
},
  data: [...
{
```

We have noticed that there is no count query  executed for these kind of URIs which might indicate that this is intended and therefore I didn't log it as a bug. 

**Describe the solution you'd like**
Results in nested results that are consistent with an entity list that is retrieve via the direct devices call.  A **next** link probably is definitely desired since there is a **prev** link if you would would grab a page further in the order:

- https://localhost:5001/api/v1/locations/008b34d8-7dfe-40f1-a422-3bff500744b8/devices?page[size]=1&page[number]=2

```
{
links: {
  self: "/api/v1/locations/008b34d8-7dfe-40f1-a422-3bff500744b8/devices?page[size]=1&page[number]=2",
  first: "/api/v1/locations/008b34d8-7dfe-40f1-a422-3bff500744b8/devices?page[size]=1",
  prev: "/api/v1/locations/008b34d8-7dfe-40f1-a422-3bff500744b8/devices?page[size]=1"
},
data: [...
```

So it feels inconsistent that you can use the links to get the prev yet have to construct the next links yourself. 
The totalResources would definitely be convenient as well since it's more consistent to the other results. 

**Describe alternatives you've considered**
Currently we will postprocess the json result and add the information ourselves, if there is a better solution, please advise. 

**Additional context**
Version 4.2.0

**Comment by bart-degreed** [comment] 2021-07-20 13:38
Hi @databrecht, thanks for bringing this up. Unless I misunderstood, this is a known limitation, tracked at #1010. If that's the case, can you please upvote that issue, so that I can close this one as a duplicate?

**Comment by bart-degreed** [comment] 2021-07-20 13:46
An alternative to post-processing would be to execute the `COUNT(*)` by yourself, inject `IPaginationContext`, and set its `TotalResourceCount` property from a custom controller/service/repository.

**Comment by databrecht** [comment] 2021-07-23 09:28
My apologies, I didn't find that ticket. Thanks for the advice! Feel free to close if it doesn't add any information to 1010

**Comment by bart-degreed** [comment] 2021-07-23 09:37
Closing as duplicate of #1010.

**Closed by bart-degreed** 2021-07-23 09:37 UTC
Labels: duplicate

**Comment by bart-degreed** [comment] 2021-11-06 11:15
@databrecht This is now fixed in the master branch. It would be great if you can try it out and let us know if that solves your case.

**Comment by databrecht** [comment] 2021-11-08 11:11
That's awesome, I'll look into it. However, at least this week I'm working on a deadline of another project. Once I have some time for the other project I'll test it out.

**Comment by databrecht** [comment] 2021-12-23 18:39
Only got it now, I upgraded to the latest version to test it and migrated to core 6. It works now, my case is solved and I can remove my workarounds, thanks!
