### ISSUE TITLE
How to add two resources at same time using same endpoint and one parent resource ?

### ISSUE THREAD

**Issue by abhinavchauhan12** [json-api-dotnet/JsonApiDotNetCore#1418] opened 2023-12-07 06:16 UTC
Lets suppose , I have following resources :- 

public class Car : Identifiable<int>
{
    [Attr] 
    public string Name { get; set; }
    
    [Attr] 
    public string Colour { get; set; }
    
   [HasOne]
    public Account CreatedBy {get; set;}
}

public class HybridCar : Identifiable<int>
{
    [Attr] 
    public string Name { get; set; }
    
    [Attr]
    public int CarId { get; set; }
  
}

Both are individual resources and have individual CRUD operations with separate controllers . Now , I want to add car resource also when i am hitting Hybridcarcontroller POST api. , so for this  I need to add the Car resource as an attribute in hyrbidcar resource , but this will override my hasone with createdBy in car resource with [Attr] ?
so how to resolve above case senerio ?

**Comment by bkoelman** [comment] 2023-12-07 13:54
It's not entirely clear to me what you're trying to accomplish, but it sounds like you're looking for [Resource inheritance](https://www.jsonapi.net/usage/resources/inheritance.html).

Also, you should never expose IDs as attributes, see https://www.jsonapi.net/usage/common-pitfalls.html#model-relationships-instead-of-foreign-key-attributes.

**Comment by bkoelman** [comment] 2023-12-12 11:36
@abhinavchauhan12 does this answer your question? Do you need this to remain open?

**Comment by abhinavchauhan12** [comment] 2023-12-14 18:38
No , I am asking here how to include one resource into another , because I want to create two resource at a time.

with the context of above example , when I am performing a CREATE operation on "HybridCar" , I also want to Create a "Car" as well. so for that reason , i need a request model that will take both "HybridCar" as well as "Car" in single request body .

As in JSON api , all request model are treated as a "Resource" , so my question is " How to add one resource into another except relationship to perform "create" on nested resource as well.

**Comment by bkoelman** [comment] 2023-12-14 23:05
In that case, this looks like a duplicate of #1421.

**Comment by abhinavchauhan12** [comment] 2023-12-18 12:14
while using Atomic operation , I am getting issue in the below line :-

                var results = await _operationsProcessor.ProcessAsync(operations, token);


Error :- System.NotImplementedException: 'No transaction support is available.'

**Comment by bkoelman** [comment] 2023-12-18 14:11
You're probably using a custom repository that doesn't implement `IRepositorySupportsTransaction`, which is a requirement for using operations. Can you share a minimal repro?

**Comment by abhinavchauhan12** [comment] 2023-12-21 04:53
For using atomic operation , we need to make a controller that inherits from ControllerBase instead of JsonApiController.

Right ?

**Comment by bkoelman** [comment] 2023-12-21 10:33
No. See the docs at https://www.jsonapi.net/usage/writing/bulk-batch-operations.html. You can also test against https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/src/Examples/JsonApiDotNetCoreExample or look at the various test cases at https://github.com/json-api-dotnet/JsonApiDotNetCore/tree/master/test/JsonApiDotNetCoreTests/IntegrationTests/AtomicOperations.

**Comment by bkoelman** [comment] 2024-01-05 00:05
Closing due to inactivity. Please create a new issue if there are follow-up questions.

**Closed by bkoelman** 2024-01-05 00:05 UTC
Labels: question
