### ISSUE TITLE
Applying Filters using JADNC

### ISSUE THREAD

**Issue by c2develop** [json-api-dotnet/JsonApiDotNetCore#775] opened 2020-05-27 19:39 UTC
## Description
We are doing a POC to implement filtering using JADNC for our app and would like to know if there are any specific examples that i could follow to implement filtering for GetAllService ?
Also should we explicitly define a sourcedefinition everytime we need filtering ?
Could the filtering be applied to the IGetAllService or is it always applied to a resource service ?
...

## Environment

- JsonApiDotNetCore Version: 3.0
- Other Relevant Package Versions:

**Comment by fdlane** [comment] 2020-05-27 21:14
I am fairly new to the library but here are some things that I found helpful.

The default filtering experience is very powerful and depending on your use cases, you may not need any custom filter implementations.

See the recently updated filtering documentation at https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/filtering.html.

If you do need custom filters, please see the examples at 
https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/filtering.html#custom-filters
and
https://json-api-dotnet.github.io/JsonApiDotNetCore/usage/resources/resource-definitions.html#custom-query-filters

You can also run the example projects in the source code to see the filters in action, specifically here...
https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/47d25a55172f9479c4e23607a30369e7fb793e89/src/Examples/JsonApiDotNetCoreExample/Definitions/UserDefinition.cs#L16

Here is an example of a simple `search` custom query 

`/api/v1/clients?filter[search]=bogus`

```C#
  public class ClientDefinition : ResourceDefinition<Client>
    {
      public ClientDefinition(IResourceGraph resourceGraph) : base(resourceGraph) { }

      public override PropertySortOrder GetDefaultSortOrder() => new PropertySortOrder
      {
        (t => new { t.DisplayName }, SortDirection.Ascending)
      };

      public override QueryFilters GetQueryFilters() => new QueryFilters
      {
        {
        "search",
        (items, filter) => items.Where(i => i.DisplayName.Contains(filter.Value))
        }
      };
    }
```

**Comment by c2develop** [comment] 2020-05-28 16:59
@fdlane  thanks for the input. I have noticed that , do i always have to register jsonapi with a dbcontext otherwise it doesnot get into the resourcedefinition . Is there an another approach ?

**Comment by fdlane** [comment] 2020-05-28 18:22
@c2develop  

From the `Client` entity example above, you can register the resource definition as 

```C#
services.AddScoped<ResourceDefinition<Client>, ClientDefinition>();
```

**Comment by c2develop** [comment] 2020-05-31 17:02
I see in the jsonapiexamples that always the resource models are same as db models , what if they are complex models such as different fields aggregated to a jsonapi model. my case is similar.
I keep getting the Cannot create a Dbset for 'ModelType' because this type is not included in the model of the context when i try to filter out an attribute on aggregated jsonapi model

**Comment by c2develop** [comment] 2020-06-01 22:00
@fdlane I did override the QueryFilters and every time i try it gives me an error Cannot create a dbset for '' because this type is not included in the model for the context. any inputs on this

**Comment by bart-degreed** [comment] 2020-07-17 08:19
The error message "Cannot create a Dbset for 'ModelType'" is coming from EF Core, not JsonApiDotNetCore. I think you're trying to query something that EF Core is not aware of, for example an unregistered database table. This may help: https://stackoverflow.com/questions/46761397/invalidoperationexception-cannot-create-a-dbset-for-role-because-this-type-is. Otherwise, please provide an example that demonstrates the problem, so we can reproduce and help.

**Comment by bart-degreed** [comment] 2020-08-11 10:47
Closing, as it looks like all questions have been answered. Feel free to create new issues is you need anything else.

**Closed by bart-degreed** 2020-08-11 10:47 UTC
