### ISSUE TITLE
Support JSONB columns

### ISSUE THREAD

**Issue by wayne-o** [json-api-dotnet/JsonApiDotNetCore#1537] opened 2024-04-25 16:24 UTC
Are there any plans to support JSONB columns atm? We are using JSONB in PGSQL and would like to use it more but JADNC doesn't support it - I think because of the IIdentifiable constraint?

**Comment by bkoelman** [comment] 2024-04-25 18:03
Hi @wayne-o, thanks for asking. Can you elaborate a bit, ie what do you expect? Is this the same as #1539?

**Comment by wayne-o** [comment] 2024-04-26 08:57
> Hi @wayne-o, thanks for asking. Can you elaborate a bit, ie what do you expect? Is this the same as #1439?

Ah yes I guess it is (I did search for JSONB and that didn't come up) , is there any time being spent on this currently? Am I right in thinking that the root complexity will stem from the IIdentifiable constraint required on Resource classes?

**Comment by bkoelman** [comment] 2024-04-27 05:52
> is there any time being spent on this currently? 

No. I'm currently the only contributor and my focus is on OpenAPI.

> Am I right in thinking that the root complexity will stem from the IIdentifiable constraint required on Resource classes?

The resource graph has no concept of complex attributes, where the nested data is keyless. This is a prerequisite for usage in query strings. I haven't thought this through yet, nor done any experiments. You're welcome to give it a try and figure out what would work best.

**Comment by bkoelman** [comment] 2024-05-04 10:08
Closing as a duplicate of #1439. Please let me know when you start working on this.

**Closed by bkoelman** 2024-05-04 10:08 UTC
Labels: enhancement
