### ISSUE TITLE
Ambiguous HTTP method for action - PostAsync (breaks support for Swagger)

### ISSUE THREAD

**Issue by mattgi** [json-api-dotnet/JsonApiDotNetCore#189] opened 2017-11-12 21:56 UTC
At present, if using a query controller and adding Swagger documentation, I receive this at runtime:

```
System.NotSupportedException: Ambiguous HTTP method for action - Api.Read.Controllers.UsersController.PostAsync (Api). Actions require an explicit HttpMethod binding for Swagger
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, ISchemaRegistry schemaRegistry)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath, String[] schemes)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
```

My setup is as vanilla as it comes:
```
using Microsoft.AspNetCore.Mvc;
using Api.Read.Models;
using JsonApiDotNetCore.Controllers;
using JsonApiDotNetCore.Services;

namespace Api.Read.Controllers
{
  [Route("[controller]")]
  public class UsersController : JsonApiQueryController<UserReadModel, string>
  {
    public UsersController(IJsonApiContext jsonApiContext, IResourceService<UserReadModel, string> resourceService) : base(jsonApiContext, resourceService)
    {
    }
  }
}
```

**Comment by jaredcnance** [comment] 2017-11-12 22:26
I haven't done any Swagger specific testing, so can you shed any light on why Swagger is expecting there to be a PostAsync method? The query controller inherits a PostAsync method, but it is [not exposed on the controller](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/src/JsonApiDotNetCore/Controllers/JsonApiQueryController.cs) since the query controller is expected to be read only. It sounds like something is either misconfigured or Swagger is making inferences based on the method signatures themselves rather than the actual ASP.Net routes exposed.

**Comment by jaredcnance** [comment] 2017-11-14 13:16
If you disable Swagger, are the routes handled appropriately? If so, this would imply that Swagger is not appropriately inferring valid ASP.Net Core routes. If the ambiguity is caused by multiple controllers, I doubt the workaround will solve anything. Can you provide a minimum example (github repository) that reproduces this situation?

**Comment by jaredcnance** [comment] 2017-12-05 23:56
Closing. Feel free to re-open if you can provide additional detail.

**Closed by jaredcnance** 2017-12-05 23:56 UTC
Labels: question
