### ISSUE TITLE
Opt out of Default Sort (by Id)

### ISSUE THREAD

**Issue by rachael-ross** [json-api-dotnet/JsonApiDotNetCore#899] opened 2020-12-01 17:57 UTC
#### DESCRIPTION

I have a scenario in which I do NOT want a default sort by Id to be applied.  Is there a way to turn off default sorting or intervene at a seam.

#### STEPS TO REPRODUCE

I have the following classes:

FundList
  - contains many Funds
      - which has a fundcategory
      - which also contains many FundData (but will always only display one which is enforced with filter)
   
I want to display a table as such: (where Fund & FundCategory fields are being displayed with FundData fields per row)

![image](https://user-images.githubusercontent.com/17603150/100775106-a9754a00-33b7-11eb-8992-82b040f97ca2.png)

Consider the following query:

`/api/v1/fundlists?include=funds,funds.category,funds.fundData&fields=id,name&fields[funds]=id,name,ticker&fields[funds.category]=name&fields[funds.fundData]=ttlGPA,prosNetExp,ret3Mo,ret1Yr,ret3Yr,ret5Yr,ret10Yr&filter[funds.fundData]=and(equals(periodYear,'2020'),equals(periodQuarter,'2'))&sort[funds.fundData]=-ttlGPA`

I need to offer sorting on FundData columns, such as GPA and ExpRatio, but since a default sort of Fund.Id is being performed, it's taking precedence over the FundData sorts.

```
SELECT [t].[Id], [t].[Name], [t1].[Id], [t1].[Name], [t1].[Ticker], [t1].[c], [t1].[Name0], [t1].[Id0], [t1].[Id1], [t1].[TtlGPA], 
[t1].[ProsNetExp], [t1].[Ret3Mo], [t1].[Ret1Yr], [t1].[Ret3Yr], [t1].[Ret5Yr], [t1].[Ret10Yr],[t1].[Id2]
FROM (
    SELECT TOP(2) [f].[Id], [f].[Name]
    FROM [FundLists] AS [f]
    ORDER BY [f].[Id]
) AS [t]
LEFT JOIN (
    SELECT [f1].[Id], [f1].[Name], [f1].[Ticker], CASE
        WHEN [f2].[Id] IS NULL THEN CAST(1 AS bit)
        ELSE CAST(0 AS bit)
    END AS [c], [f2].[Name] AS [Name0], [f2].[Id] AS [Id0], [f0].[Id] AS [Id1], [t0].[TtlGPA], [t0].[ProsNetExp], [t0].[Ret3Mo], 
	[t0].[Ret1Yr], [t0].[Ret3Yr], [t0].[Ret5Yr], [t0].[Ret10Yr], [t0].[Id] AS [Id2], [f0].[FundListId]
    FROM [FundListFunds] AS [f0]
    INNER JOIN [Funds] AS [f1] ON [f0].[FundId] = [f1].[Id]
    LEFT JOIN [FundCategories] AS [f2] ON [f1].[CategoryId] = [f2].[Id]
    LEFT JOIN (
        SELECT [f3].[TtlGPA], [f3].[ProsNetExp], [f3].[Ret3Mo], [f3].[Ret1Yr], [f3].[Ret3Yr], [f3].[Ret5Yr], [f3].[Ret10Yr], 
		[f3].[Id], [f3].[FundId]
        FROM [FundData] AS [f3]
        WHERE ([f3].[PeriodYear] = 2020) AND ([f3].[PeriodQuarter] = 2)
    ) AS [t0] ON [f1].[Id] = [t0].[FundId]
) AS [t1] ON [t].[Id] = [t1].[FundListId]
ORDER BY [t].[Id], [t1].[Id], [t1].[Id1], [t1].[TtlGPA] DESC, [t1].[Id2]
```

#### EXPECTED BEHAVIOR

Returned records to be sorted by the field indicated in querystring.

#### ACTUAL BEHAVIOR

It's being ordered as a tertiary column instead.

#### VERSIONS USED
- JsonApiDotNetCore version: master branch as of 11/15/2020
- ASP.NET Core version: 3.1
- Entity Framework Core version: 3.1.10
- Database provider: SQL Server

**Comment by bart-degreed** [comment] 2020-12-01 18:09
Your query string does not indicate any sorting at top-level. Instead, use:

```
&sort=name
&sort[funds.fundData]=-ttlGPA
```

Alternatively, you can implement custom sorting from a resource definition (see [here](https://www.jsonapi.net/usage/resources/resource-definitions.html#default-sort-order)).

**Comment by rachael-ross** [comment] 2020-12-01 18:15
Thanks, @bart-degreed , but that doesn't work and I can't do it on a resource definition. The FundList.Id and Fund.Id are being applied as primary and secondary sorts (and isn't applied at the time that OnApplySort is called) and it's the FundData.TtlGPA column that I want as the primary sort.

**Comment by bart-degreed** [comment] 2020-12-02 10:42
Thanks, I think I understand your use case now. And it sounds like a legitimate reason for us to provide an option to disable default sorting by ID. However, I wonder if such an option would actually solve your use case. Let me explain.

When sending `GET /api/v1/fundlists?include=funds&sort=name`, we generate a LINQ query along the lines of:

```c#
source
    .Include(fundlist => fundlist.Funds)
    .OrderBy(fundlist => fundlist.Name)
```

And when sending `GET /api/v1/fundlists?include=funds&sort[funds]=name`, we generate:

```c#
source
    .Include(fundlist => fundlist.Funds)
    .OrderBy(fundlist => fundlist.Id) // automatic
    .Select(fundlist => new Fundlist
    {
        Name = fundlist.Name,
        Funds = fundlist.Funds
            .OrderBy(fund => fund.Name)
            .ToList()
    })
```

Assuming we provide an option to disable automatic sort by ID and it is activated, the line with comment is omitted in the last example. With that change, the query means:
- Give me a list of all FundList objects, unordered.
- Within each FundList object, order the list of child Fund objects by name

What you actually need, I believe, is a way to set top-level sorting based on a condition of a child table, such as:

```c#
source
    .Include(fundlist => fundlist.Funds)
    .ThenInclude(fund => fund.Category)
    .Include(fundlist => fundlist.Funds)
    .ThenInclude(fund => fund.FundData)
    .Select(fundlist => new Fundlist
    {
        Name = fundlist.Name,
        Funds = fundlist.Funds
            .OrderBy(fund => fund.fundData.SelectMany(x => x).TtlGPA) // <---- ?
            .ToList()
    })
```

which is not something we have syntax for to express in a query string or resource definition. Instead you could accomplish this by overriding `EntityFrameworkCoreRepository.GetAll`, where you can add custom C# expressions to the `IQueryable` that is being sent to EF Core.

In case I misunderstand, it helps if you can provide the LINQ query you expect JADNC to produce.

**Comment by rachael-ross** [comment] 2020-12-02 23:53
@bart-degreed  Yep, you're on point.

Although I knew the Funds themselves were not going to be ordered by the child FundData columns, I was thinking the "included" FundData in the output would be ordered and I could instruct the UI dev to parse those in the order returned and then grab their Fund and FundCategory name for each bound row (as a workaround), but that probably won't work with how the object graph is serialized, will it?

Being able to sort the higher-level objects per a child object property would be awesome since this presenting parent property values inline with child data is a fairly common scenario in biz apps.

**Comment by rachael-ross** [comment] 2020-12-04 04:39
Well..... crap! I added an option to opt out of default sorting "JsonApiOptions.EnableDefaultSortById" and applied to QueryLayerComposer::GetSort  and it works as expected - BUT for my specific scenario, EF Core is adding the Order By Id clause for top level due to the nature of the specific query scenario. So I'll have to figure out something else.  

https://github.com/dotnet/efcore/issues/6861 


```
  protected virtual SortExpression GetSort(IReadOnlyCollection<QueryExpression> expressionsInScope, ResourceContext resourceContext)
        {
            if (expressionsInScope == null) throw new ArgumentNullException(nameof(expressionsInScope));
            if (resourceContext == null) throw new ArgumentNullException(nameof(resourceContext));

            var sort = expressionsInScope.OfType<SortExpression>().FirstOrDefault();

            sort = _resourceDefinitionAccessor.OnApplySort(resourceContext.ResourceType, sort);

            if (sort == null && _options.EnableDefaultSortById)
            {
                var idAttribute = GetIdAttribute(resourceContext);
                sort = new SortExpression(new[] {new SortElementExpression(new ResourceFieldChainExpression(idAttribute), true)});
            }

            return sort;
        }


```

**Comment by bart-degreed** [comment] 2020-12-05 10:11
Databinding against the `included` array from json response sounds like a bad idea to me. It was designed to efficiently transmit the requested data and is not in the shape you need it to be. It has no guaranteed order and duplicates are omitted.

When I look at the grid you're trying to produce, FundData seems to be the primary data source, so I would query that instead. You can then just pass a simple sort without any nestings. The first two columns (parent name and category) can be side-loaded via include (not sortable).

To render the full page, I would first retrieve a list of all funds (id + name) and cache that. Have all tables collapsed initially. When user clicks the expand button, run the next query to fill the grid.

```http
GET /api/v1/funddatas/?filter=equals(parentfund.id,'1')&sort=ttlpga&page[number]=2&include=parentfund&fields[parentfund]=name HTTP/1.1
```

A word of caution though: json:api is a REST spec for transferring resources. It assumes resources have a fixed structure. What you're trying to produce are view models to render a UI, which is something else entirely. They typically contain duplicate data that is aggregated and projected over multiple sources, shaped in a format to make data binding easy. This is not something json:api provides and it is not something JsonApiDotNetCore can help you with. If that's what you need, a custom EF Core query or a custom SQL View, combined with a UI-specific endpoint, may be more appropriate in your case. But that is no longer a REST API.

**Comment by rachael-ross** [comment] 2020-12-06 02:59
Agreed! I didn't mean to literally bind though. What I've ended up doing is flattening the data into a database view, creating a resource class against that view so it's fully sortable.

**Closed** 2020-12-10 14:54 UTC
