### ISSUE TITLE
getting a CommitAysnc in type 'Jsonapidotnetcore.extension.safetransactionproxy' does not have implementation

### ISSUE THREAD

**Issue by c2develop** [json-api-dotnet/JsonApiDotNetCore#740] opened 2020-05-11 15:25 UTC
## Description
Added the jsonapidotnetcore nuget package to my project.Registered the jsonapi in the configure services in startup.cs and i keep getting this issue when i try to run my application.
services.AddJsonApi<dbcontext>(options=> {options.namespace="api/v1, options.BuildResourceGraph(builder)=>{builder.AddResource<Domain>();}});
...
Do not know what is causing this issue. 
## Environment

- JsonApiDotNetCore Version: 
- Other Relevant Package Versions:

**Comment by bart-degreed** [comment] 2020-05-11 15:50
Assuming you're on 3.x (which I know nothing about), this sounds like a duplicate of #726.

**Comment by c2develop** [comment] 2020-05-11 17:45
Yes im using .net core 3.1 . Does that mean JADNC 3.1.0 does not support the EF 3.1.2 ?

**Comment by bart-degreed** [comment] 2020-05-11 19:05
I joined this project recently and have no experience with JADNC 3.x, so I wouldn't know. But looking at the Releases tab, I think the latest update to JADNC 3.x was from before .NET Core 3.x was released.

**Comment by bart-degreed** [comment] 2020-05-11 19:06
JADNC v4-alpha5 fully support .NET Core 3.1, though.

**Comment by c2develop** [comment] 2020-05-11 19:34
Thanks @bart-degreed  , v4-alpha5 worked, but is there a work around to use JADNC 3.1 with EFcore 3.1 ??

**Comment by bart-degreed** [comment] 2020-05-11 19:46
See #726.

**Closed** 2020-05-14 12:40 UTC
