### ISSUE TITLE
HasManyThrough always returns data:null but includes returns data

### ISSUE THREAD

**Issue by sarahentzel** [json-api-dotnet/JsonApiDotNetCore#491] opened 2019-04-04 19:40 UTC
## Description
Running the JsonApiDotNetCoreExample, `http://localhost:1479/api/v1/articles/1/tags` returns `{"data":null}` but  `http://localhost:1479/api/v1/articles/1?include=tags` returns the tags:
```json
{  
   "data":{  
      "attributes":{  
         "name":"Article 1 about good stuff"
      },
      "relationships":{  
         "author":{  
            "links":{  
               "self":"http://localhost:1479/api/v1/articles/1/relationships/author",
               "related":"http://localhost:1479/api/v1/articles/1/author"
            },
            "data":{  
               "type":"authors",
               "id":"1"
            }
         },
         "tags":{  
            "links":{  
               "self":"http://localhost:1479/api/v1/articles/1/relationships/tags",
               "related":"http://localhost:1479/api/v1/articles/1/tags"
            },
            "data":[  
               {  
                  "type":"tags",
                  "id":"1"
               }
            ]
         }
      },
      "type":"articles",
      "id":"1"
   },
   "included":[  
      {  
         "attributes":{  
            "name":"Good Stuff"
         },
         "type":"tags",
         "id":"1"
      }
   ]
}
```

## Environment 

- JsonApiDotNetCore Version: I've tried using release 3.0.0, develop and master branches
- Other Relevant Package Versions:

**Comment by sarahentzel** [comment] 2019-04-10 18:13
@wisepotato Were you able to get data with  api/v1/articles/1/tags as well as api/v1/articles/1?include=tags (after you fixed it?)

**Comment by wisepotato** [comment] 2019-04-11 09:40
Is there a specific issue you are referring to? This could very well not be implemented yet

**Comment by sarahentzel** [comment] 2019-04-11 14:23
It *seems* like it has been implemented based on issue #453 which sounds like the same issue solved.

**Comment by maurei** [comment] 2019-04-23 07:45
@sarahentzel did you manage to work this out? Is this still an issue?

**Comment by sarahentzel** [comment] 2019-04-23 10:33
It is still an issue.

**Comment by maurei** [comment] 2019-04-23 16:17
OK, we're currently working on releasing a new version, should be finished somewhere this week. Will look into this after that. If you could meanwhile make a branch with a test that reproduces the exact error, it would greatly aid me in quickly fixing it :-)

**Comment by sarahentzel** [comment] 2019-04-23 19:30
Permission to json-api-dotnet/JsonApiDotNetCore.git denied to sarahentzel

**Comment by wisepotato** [comment] 2019-04-23 20:11
You can fork the current repository, and then create a pull request, it will show us the test

**Comment by rjacquemin** [comment] 2019-05-08 20:45
we did encounter same issue 

![image](https://user-images.githubusercontent.com/12820060/57406958-0d219c00-71b0-11e9-9475-e5d7407547c1.png)

calling `"related": "/api/admin/packs/2/genres"`
![image](https://user-images.githubusercontent.com/12820060/57407227-ad77c080-71b0-11e9-8472-6d8cd75524ef.png)

calling with include 
![image](https://user-images.githubusercontent.com/12820060/57407210-a486ef00-71b0-11e9-9538-bb12ef6fa07b.png)

**Comment by adu89** [comment] 2019-05-08 21:31
@rjacquemin @wisepotato 

Looks like the issue is in ResourceGraph.cs 

![image](https://user-images.githubusercontent.com/10604159/57409509-786e6c80-71b6-11e9-9672-ff978dea4f26.png)

Looks like the variabe "navigationProperty" does not reflect the one specified by [HasManyThrough(nameof(...)] attribute on the original entity.

**Comment by bart-degreed** [comment] 2020-05-13 12:49
On the current master branch, I cannot reproduce the originally posted problem.

```http
GET http://localhost:1479/api/v1/articles/1/tags HTTP/1.1
```

```json
{
  "links": {
    "self": "http://localhost:1479/api/v1/articles/1/tags"
  },
  "data": [
    {
      "type": "tags",
      "id": "1",
      "attributes": {
        "name": "vrre051f7t"
      },
      "links": {
        "self": "http://localhost:1479/api/v1/tags/1"
      }
    }
  ]
}
```

```http
GET http://localhost:1479/api/v1/articles/1?include=tags HTTP/1.1
```

```json
{
  "links": {
    "self": "http://localhost:1479/api/v1/articles/1?include=tags"
  },
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      "name": "None for you Glen Coco"
    },
    "relationships": {
      "author": {
        "links": {
          "self": "http://localhost:1479/api/v1/articles/1/relationships/author",
          "related": "http://localhost:1479/api/v1/articles/1/author"
        }
      },
      "tags": {
        "links": {
          "self": "http://localhost:1479/api/v1/articles/1/relationships/tags",
          "related": "http://localhost:1479/api/v1/articles/1/tags"
        },
        "data": [
          {
            "type": "tags",
            "id": "1"
          }
        ]
      },
      "identifiableTags": {
        "links": {
          "self": "http://localhost:1479/api/v1/articles/1/relationships/identifiableTags",
          "related": "http://localhost:1479/api/v1/articles/1/identifiableTags"
        }
      }
    },
    "links": {
      "self": "http://localhost:1479/api/v1/articles/1"
    }
  },
  "included": [
    {
      "type": "tags",
      "id": "1",
      "attributes": {
        "name": "vrre051f7t"
      },
      "links": {
        "self": "http://localhost:1479/api/v1/tags/1"
      }
    }
  ]
}
```

Any reason not to close this?

**Closed** 2020-07-17 08:42 UTC
Labels: needs-investigation
