### ISSUE TITLE
Null Reference in TypeMatchFilter Middleware with non-JADNC Controller

### ISSUE THREAD

**Issue by joshhubers** [json-api-dotnet/JsonApiDotNetCore#405] opened 2018-09-13 15:22 UTC
## Description
I'm getting a

```
    System.NullReferenceException: Object reference not set to an instance of an object.
    at JsonApiDotNetCore.Middleware.TypeMatchFilter.OnActionExecuting(ActionExecutingContext context) in 
C:\projects\jsonapidotnetcore\src\JsonApiDotNetCore\Middleware\TypeMatchFilter.cs:line 34

```
Using a standard dotnet Core Controller when returning a ```Json(result)``` of type string.
My code is as follows:

```
namespace Foo.Controllers
{
    [Authorize]
  public class UploadController : Controller
  {
    IPhotoService _photoService;

    public UploadController(IPhotoService photoService)
    {
      _photoService = photoService;
    }

    [Route("api/v1/attachments/upload")]
    [HttpPost]
    public async Task<IActionResult> PostFileAsync(IFormFile file)
    {
      if(file == null || file.Length == 0)
        return Content("No content in file or file not uploaded");

      string path = await _photoService.UploadPhotoAsync(file);
      
      return Json(path);
    }
  }
}

```

Looking at the code I'm gonna guess it's something to do with the ```IsJsonApiRequest``` not filtering replies properly?

## Environment

- JsonApiDotNetCore Version: 2.5.2
- Other Relevant Package Versions:

**Comment by joshhubers** [comment] 2018-09-13 15:34
Rolling back to 2.5.0 before the middleware update fixed the issue for me for now.

**Comment by jaredcnance** [comment] 2018-09-13 18:39
Thanks for reporting this. Currently, we only check the `Content-Type` and assume that all `application/vnd.api+json` `POST|PATCH` requests should be handled by this filter. Are you using this content type in your non-json:api requests? We may be able to run a check against the activating controller type, but I'll need to verify that's possible.

**Comment by joshhubers** [comment] 2018-09-14 12:59
Yes, I am using this content type. Good to know!

**Comment by medokin** [comment] 2019-02-10 20:25
This bug was resolved with https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/457

**Comment by jaredcnance** [comment] 2019-02-11 15:26
Thanks @medokin! Closing this. Please re-open if the issue is not resolved.

**Closed by jaredcnance** 2019-02-11 15:26 UTC
Labels: needs-investigation
