### ISSUE TITLE
PATCH Successfully but Return Data is Null

### ISSUE THREAD

**Issue by lrfahmi** [json-api-dotnet/JsonApiDotNetCore#870] opened 2020-10-31 18:51 UTC
## Description
I tried to PATCH the _department_ resource. Request body as below:

```
PATCH /departments/10
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
    "data": {
        "type": "departments",
        "id": "10",
        "attributes": {
            "name": "Department 10",
            "description": ""
        }
    }
}
```

The data has been changed successfully, but the response data received is: null.

```
{
    "links": {
        "self": "http://localhost:5000/departments/10"
    },
    "data": null
}
```

The response should have received changed data right?
...

## Environment

- JsonApiDotNetCore Version: 4.0.0-beta1

**Comment by bart-degreed** [comment] 2020-10-31 22:35
This is by design. See the json:api spec. We only return the changed resource when the update caused side effects in attributes that the client cannot know about.

**Comment by bkoelman** [comment] 2020-11-01 01:27
Relevant quote from the json:api spec:

> 204 No Content
If an update is successful and the server doesn’t update any fields besides those provided, the server MUST return either a 200 OK status code and response document (as described above) or a 204 No Content status code with no response document.

**Comment by bkoelman** [comment] 2020-11-01 01:50
This is actually broken in master (which returns 200 with data:null instead of 204), but fixed in #851, which we'll merge before the next release.

**Comment by lrfahmi** [comment] 2020-11-01 04:14
Ok if it's like that. I'm just learning the json: api spec. So, does PATCH not return modified data?

Thank you for the quick response.

**Comment by bart-degreed** [comment] 2020-11-01 16:08
Only when side effects occur. For example, if you have a database trigger that sets LastModifiedAt column on each update. The api user cannot know, so we send back the full resource. If there are no side effects, we don't send back the resource for efficiency. The client already knows what has changed.

**Comment by lrfahmi** [comment] 2020-11-01 17:51
Thanks for the information. With this explanation, I can understand.

**Closed** 2020-11-01 21:27 UTC
Labels: bug
