### ISSUE TITLE
Bug: Broken casing of JSON attributes

### ISSUE THREAD

**Issue by bart-degreed** [json-api-dotnet/JsonApiDotNetCore#626] opened 2019-11-21 13:27 UTC
## Description
After updating my local clone to https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/619, attribute casing in JSON responses has changed.

Before:
```json
      "attributes": {
        "title": "First Video",
        "summary": "Summary for first video",
        "duration-in-seconds": null,
        "url": "https://www.youtube.com/watch?v=video1",
        "image-url": null,
        "language": null,
        "published-at": null,
        "created-at": "0001-01-01T00:00:00",
        "modified-at": "0001-01-01T00:00:00",
        "is-deleted": false,
        "provider-code": null,
        "external-id": null
      },
```

```json
      "attributes": {
        "title": "First Video",
        "summary": "Summary for first video",
        "durationInSeconds": null,
        "url": "https://www.youtube.com/watch?v=video1",
        "imageUrl": null,
        "language": null,
        "publishedAt": null,
        "createdAt": "0001-01-01T00:00:00",
        "modifiedAt": "0001-01-01T00:00:00",
        "isDeleted": false,
        "provider-code": null,
        "externalId": null
      },
```

**Comment by maurei** [comment] 2019-11-21 14:54
In v4 camelCase is the standard casing convention, by which we're following new json:api recommendations, see https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/618.  You can switch back to kebab-case by setting the `KebabCaseFormatter` as the implementation of `IResourceNameFormatter`:

```c#
// make sure you call this BEFORE `.AddJsonApi( .. ) 
services.AddSingleton<IResourceNameFormatter, KebabCaseFormatter>();
```

See tests related to `KebabCaseApplicationFactory.cs` in `JsonApiDotNetCoreExampleTests`.


> "provider-code": null,

Is that really the response you're getting? That would indicate a serious bug. I'm going to assume that is not the case since all the rest is camelcase. Let me know if otherwise. 

Closing as not a bug

Thanks for the issues you've been opening up, will go through them soon

**Closed by maurei** 2019-11-21 14:54 UTC

**Comment by bart-degreed** [comment] 2019-11-21 15:05
Thanks, this works for me. 

`provider-code` has an explicit name in its `AttrAttribute`.
